### ISSUE TITLE
"Timeout while loading URL" from Generic Camera

### ISSUE THREAD

**Issue by yorb** [dm82m/hassio-addons#49]
Hi, thanks for the add-on! I know this is old and most people have given up on this, but I just (foolishly) got an Argus Eco Ultra and wanted to see if I could get it running. I already have Docker Wyze Bridge running in HA, so the only config difference I've made for Neolink is to use 8555 instead of 8554 since that's in use.

It runs, connects to the camera (via relay), but when I try to add the camera with Generic Camera integration I get "Timeout while loading URL". Any ideas? I've tried both this repo and the Neolink-latest one.

This is my very minimal config:
```toml
bind = "0.0.0.0"

bind_port = 8555

[[cameras]]
name = "Patio"
username = "admin"
password = "****"

uid = "****"
```
